name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        shell: bash
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Install dependencies
        shell: bash
        run: ./vcpkg/vcpkg install catch2 sdl2

      - name: Configure CMake
        shell: bash
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        shell: bash
        run: cmake --build build --config Release

      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        run: ./build/tests/gbemu-tests

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: ./build/Release/tests/gbemu-tests.exe